"""
Django settings for EducResa project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(+26^&*%w%7pe1=_ytp8l^w3ax=ws_l&yzyfiz@$j#t1im-14j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'comptes',
    'EducResa',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',# Pour servir les fichiers statiques avec Daphne
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EducResa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'Templates',
            'comptes/templates/comptes',
            'chat/templates/chat',
            'Templates/ENSAE',
            'Templates/ISSEA',
            'Templates/ENSEA',
            'Templates/ENSAE/AS1',
            'Templates/ENSAE/AS2',
            'Templates/ENSAE/AS3',
            'Templates/ENSAE/ISEP1',
            'Templates/ENSAE/ISEP2',
            'Templates/ENSAE/ISE1',
            'Templates/ENSAE/ISE2',
            'Templates/ENSAE/ISE3',
            'Templates/ENSEA/AS1',
            'Templates/ENSEA/AS2',
            'Templates/ENSEA/AS3',
            'Templates/ENSEA/ISE1',
            'Templates/ENSEA/ISE2',
            'Templates/ENSEA/ISE3',
            'Templates/ISSEA/AS1',
            'Templates/ISSEA/AS2',
            'Templates/ISSEA/AS3',
            'Templates/ISSEA/ISEL1',
            'Templates/ISSEA/ISEL2',
            'Templates/ISSEA/ISE1',
            'Templates/ISSEA/ISE2',
            'Templates/ISSEA/ISE3',
            'Templates/ENSAE/AS1/semestre2',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EducResa.wsgi.application'

ASGI_APPLICATION = 'EducResa.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],  # S'assurez que Redis soit en cours d'exécution sur ce port
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    # os.path.join(BASE_DIR, 'connection/static/connection'), // au cas ou dans l'application 'connection on a cree un autre dossier static contenant le dossier 'connection ou se trouve les fichiers statiques
]

STATIC_ROOT = os.path.join(BASE_DIR, 'C:/Users/SMART/Desktop/Django/EducResa/EducResa/staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# Configuration des fichiers et des dossiers pour les photos d'utilisateur
MEDIA_URL = 'documents/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'documents')

USER_EMAIL = 'email'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'christnzonde@gmail.com'
EMAIL_HOST_PASSWORD = 'nlrk qjiy wmfm cxdj' # Mot de passe d'applications généré par Google
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
CONTACT_EMAIL = 'christnzonde@gmail.com'  # L'email qui reçoit les messages du formulaire


