# Generated by Django 3.2.5 on 2024-09-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_response_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
