# Generated by Django 3.2.5 on 2024-09-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_visible',
            new_name='visible',
        ),
    ]
