# Generated by Django 5.0.6 on 2024-07-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(null=True, upload_to='documents/photosUsers/'),
        ),
    ]
