# Generated by Django 5.0.6 on 2024-07-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_utilisateur_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ecole', models.CharField(max_length=50)),
                ('classe', models.TextField(max_length=50)),
                ('semestre', models.TextField(max_length=50)),
                ('matiere', models.TextField(max_length=50)),
                ('titre', models.TextField(max_length=50)),
                ('annee', models.TextField(max_length=50)),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('doc', models.FileField(upload_to='Anciens_Sujets/')),
            ],
        ),
    ]
