# Generated by Django 5.0.6 on 2024-07-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_sujets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujets',
            name='doc',
            field=models.FileField(blank=True, upload_to='Anciens_Sujets/'),
        ),
    ]
