# Generated by Django 5.0.6 on 2024-07-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_corriges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corriges',
            name='doc',
            field=models.FileField(blank=True, unique=True, upload_to='Corriges/'),
        ),
        migrations.AlterField(
            model_name='sujets',
            name='doc',
            field=models.FileField(blank=True, unique=True, upload_to='Anciens_Sujets/'),
        ),
    ]
