# Generated by Django 5.0.6 on 2024-07-17 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_alter_corriges_doc_alter_sujets_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matiere', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('fichier', models.FileField(unique=True, upload_to='DocumentsDivers/')),
                ('description', models.TextField(max_length=1000)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.utilisateur')),
            ],
        ),
    ]
