# Generated by Django 3.2.5 on 2024-10-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_utilisateur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujets',
            name='classe',
            field=models.CharField(choices=[('AS1', 'AS1'), ('AS2', 'AS2'), ('AS3', 'AS3'), ('ISEP1', 'ISEP1'), ('ISEL1', 'ISEL1'), ('ISEP2', 'ISEP2'), ('ISEL2', 'ISEL2'), ('ISEP3', 'ISEP3'), ('ISEL3', 'ISEL3'), ('ISE1_maths', 'ISE1_maths'), ('ISE1_eco', 'ISE1_eco'), ('ISE2', 'ISE2'), ('ISE3', 'ISE3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sujets',
            name='ecole',
            field=models.CharField(choices=[('ENSAE', 'ENSAE'), ('ISSEA', 'ISSEA'), ('ENSEA', 'ENSEA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sujets',
            name='semestre',
            field=models.CharField(choices=[('Semestre 1', 'Semestre 1'), ('Semestre 2', 'Semestre 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sujets',
            name='titre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
